spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: financeiro

integration:
  payment-adapter-api:
    url: http://localhost:8081/api
    name: PaymentAdapter


server:
  port: 8080

management:
  server:
    port: 8080
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: info,health, env