spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: aluno
      #uri: mongodb://localhost:27017/aluno


##usuario quanto sistema

security:
  oauth2:
    client:
      scope: password
      client-id: poc-puc
      client-secret: 123

